### PR TITLE
fixes a bug with the csv file handling between py2 and 3

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Uhm, want to make this build on Alfred before merging.

**Comment by giorgiosironi** [comment]
Build on Alfred works, but we are missing https://github.com/elifesciences/builder-private/blob/145106c8dd0cb910b5dd9d15cbd077e16a35202c/pillar/elife-libraries.sls#L7 for its final stage, can someone add it?

**Comment by seanwiseman** [comment]
Just opened a [PR](https://github.com/elifesciences/builder-private/pull/134) adding the token.

**Comment by giorgiosironi** [comment]
Now green.

**Comment by gnott** [comment]
Approved and passing, I will merge to get Alfred builds happening.

**Pull request merged**
