### PR TITLE
adds pep508 url to setup.py 'install_requires'

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by gnott** [comment]
I'm noticing this PR is still open, @lsh-0 I wonder if the detail this adds may be resolved now that `elifearticle` is now published at pypi and can be installed using pip?

**Comment by lsh-0** [comment]
what is elife-article and what does it do? https://github.com/elifesciences/elife-article

it looks like a subset of elife-tools ?

I forget why I opened this PR.

**Comment by gnott** [comment]
> what is elife-article and what does it do? https://github.com/elifesciences/elife-article

It primarily contains classes which are used by other Python libraries (https://github.com/elifesciences/elife-article/network/dependents), and it was a result of refactoring the old PoA generation code into more reusable parts.

I continue to think the change proposed in this PR is not longer required, since `elifearticle` is now a package available for install from `pypi`, which has been probably done this year as a part of the Python library release pipeline configuration. Maybe at some point `setuptools` was unable to locate the dependency because it was a defined in a "private" repo?

**Comment by gnott** [comment]
I'll close this PR based on previous discussions.

**Pull request closed without merging**
